readme + setup update

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -10,12 +10,20 @@ BACKUPDIR=~/"$(date +"%d-%m-%Y_%H%M%S")"_dotfiles_backup
 
 if [ -d "$BACKUPDIR" ]; then
     echo "The directory "$BACKUPDIR" already exists."
+    echo "Aborting..."
     return 1 2>/dev/null
     exit 1
 fi
 
 echo "Creating backup directory..."
 mkdir "$BACKUPDIR"
+
+if [ ! -d "$BACKUPDIR" ]; then
+    echo "The directory "$BACKUPDIR" could not be created succesfully."
+    echo "Aborting..."
+    return 1 2>/dev/null
+    exit 1
+fi
 
 #Move files into backup directory if they exist
 echo "Moving existing configuration files..."
@@ -132,6 +140,10 @@ ln -s ~/.config/nvim/config/themes/pywal.vim ~/.config/nvim/active_theme.vim
 ##################
 #  post install  #
 ##################
+
+#make zsh default shell
+chsh -s $(which zsh)
+
 echo "Manual adjustments might be required:"
 echo "Install the pywal firefox extension"
 echo "Set the iterm font"
