bunt now supports existing files

diff --git a/bunt/build-new-theme b/bunt/build-new-theme
--- a/bunt/build-new-theme
+++ b/bunt/build-new-theme
@@ -1,35 +1,50 @@
 #!/bin/bash
-DIR=$HOME/Dropbox/Wallpapers
+DIR=$HOME/.config/bunt
 GET_WALLPAPER=true
 
-while [ "$GET_WALLPAPER" == "true" ]
-do
-    # fetch random wallpaper from unsplash
-    echo -n "Fetching a random wallpaper..."
-    wget -O $DIR/today https://source.unsplash.com/random/1920x1080 > /dev/null 2>&1
-    echo " ✔️"
+if [ ! $# -eq 0 ]; then
+    if [ ! -f "$1" ]; then
+        echo "$1 is not a file! Aborting..."
+        return 1 2>/dev/null
+        exit 1
+    fi
 
-    # remove manually wal cache
-    echo -n "Removing previous wal cache..."
-    rm -rf "$HOME/.cache/wal"
-    echo " ✔️"
+    cp -v "$1" "$DIR/wallpaper"
 
-    # generate colors palette, skip setting wallpaper
-    echo "Generating colours..."
-    wal -i $DIR/today --backend haishoku
+    wal -i $DIR/wallpaper --backend haishoku
 
-    imgcat --height 10 $DIR/today
+    imgcat --height 10 $DIR/wallpaper
 
-    while true; do
-        echo "Are you happy with this theme?"
-        read -p "" yn
-        case $yn in
-            [Yy]* ) GET_WALLPAPER=false; break;;
-            [Nn]* ) GET_WALLPAPER=true; break;;
-            * ) echo "Please answer yes or no.";;
-        esac
+else
+    while [ "$GET_WALLPAPER" == "true" ]
+    do
+        # fetch random wallpaper from unsplash
+        echo -n "Fetching a random wallpaper..."
+        wget -O $DIR/wallpaper https://source.unsplash.com/random/1920x1080 > /dev/null 2>&1
+        echo " ✔️"
+
+        # remove manually wal cache
+        echo -n "Removing previous wal cache..."
+        rm -rf "$HOME/.cache/wal"
+        echo " ✔️"
+
+        # generate colors palette, skip setting wallpaper
+        echo "Generating colours..."
+        wal -i $DIR/wallpaper --backend haishoku
+
+        imgcat --height 10 $DIR/wallpaper
+
+        while true; do
+            echo "Are you happy with this theme?"
+            read -p "" yn
+            case $yn in
+                [Yy]* ) GET_WALLPAPER=false; break;;
+                [Nn]* ) GET_WALLPAPER=true; break;;
+                * ) echo "Please answer yes or no.";;
+            esac
+        done
     done
-done
+fi
 
 #apply to spotify
 echo "Applying new theme to spotify..."
